exports.up = function(knex, Promise) {
  return knex.schema.createTable('nanny_account_info', table => {
        table.increments('id').primary()
        table.string('username', 60)
        table.string('password', 60)
        table.string('first_name', 60)
        table.string('last_name', 60)
        table.string('phone_number')
        table.string('email_address')
        table.integer('age')
        table.string('gender', 60)
        table.string('photo_url', 100)
        table.string('city', 60)
        table.string('state', 60)
        table.integer('years_experience')
        table.integer('hourly_rate')
        table.boolean('surfing', 60)
        table.boolean('kayaking', 60)
        table.boolean('rock_climbing', 60)
        table.boolean('skateboarding', 60)
        table.boolean('hiking', 60)
        table.boolean('mountain_biking', 60)
        table.boolean('skiing', 60)
        table.boolean('snowboarding', 60)
        table.string('background', 255)
        table.string('education', 255)
        table.boolean('first_aid', 60)
        table.boolean('cpr', 60)
        table.boolean('lifeguard', 60)
        table.string('other_certs', 255)
        table.string('car_make', 60)
        table.string('car_model', 60)
        table.integer('car_year')  
  })
};

exports.down = function(knex, Promise) {
  return knex.schema.dropTableIfExists('nanny_account_info')
};
