
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('nanny_account_info').del()
    .then(function () {
      // Inserts seed entries
      return knex('nanny_account_info').insert([
        {
          username: 'howie123',
          password: 'password',
          first_name: 'Howard',
          last_name: 'Crawford',
          phone_number: '303-102-1238',
          email_address: 'howieboy@gmail.com',
          age: 31,
          gender: 'male',
          photo_url: 'https://randomuser.me/api/portraits/men/15.jpg',
          city: 'Denver',
          state: 'CO',
          years_experience: 10,
          hourly_rate: 25,
          surfing: true,
          kayaking: false,
          rock_climbing: false,
          skateboarding: true,
          hiking: false,
          mountain_biking: true,
          skiing: false,
          snowboarding: true,
          background: 'I grew up in Dillion, CO where I snowboarded and skated most of my childhood and adult life.  I also lived in HI for 6 years after college where I taught surf lessons.',
          education: 'bachelor degree',
          first_aid: true,
          cpr: true,
          lifeguard: true,
          other_certs: '',
          car_make: 'Subaru',
          car_model: 'Forrester',
          car_year: 2011 
        },
        {
          username: 'ava.herrera12@example.com',
          password: 'capricor',
          first_name: 'Ava',
          last_name: 'Herrera',
          phone_number: '(214)-143-6221',
          email_address: 'ava.herrera12@example.com',
          age: 23,
          gender: 'female',
          photo_url: 'https://randomuser.me/api/portraits/women/17.jpg',
          city: 'Denver',
          state: 'CO',
          years_experience: 5,
          hourly_rate: 25,
          surfing: false,
          kayaking: false,
          rock_climbing: true,
          skateboarding: false,
          hiking: true,
          mountain_biking: false,
          skiing: true,
          snowboarding: false,
          background: 'I have been climbing since childhood at my local gym and have competed in multiple competitions.  I also have climbed 5 14ers and am very comfortable hiking.',
          education: 'Masters',
          first_aid: true,
          cpr: true,
          lifeguard: false,
          other_certs: 'WFR',
          car_make: 'Jeep',
          car_model: 'Wrangler',
          car_year: 2015
        },
        {
          username: 'erica.byrd65@example.com',
          password: 'bryan',
          first_name: 'Erica',
          last_name: 'Byrd',
          phone_number: (720)-115-5719,
          email_address: 'erica.byrd65@example.com',
          age: 38,
          gender: 'female',
          photo_url: 'https://randomuser.me/api/portraits/women/53.jpg',
          city: 'Denver',
          state: 'CO',
          years_experience: 20,
          hourly_rate: 24,
          surfing: false,
          kayaking: true,
          rock_climbing: false,
          skateboarding: false,
          hiking: true,
          mountain_biking: false,
          skiing: true,
          snowboarding: false,
          background: 'I was a middle school teacher for 10 years.  I was also an Assistant Director at Camp Pines in PA for 7 years.  I am an avid whitewater kayaker with years of experience as a guide here in CO.',
          education: 'Bachelors',
          first_aid: false,
          cpr: false,
          lifeguard: true,
          other_certs: 'Whitewater Rescue',
          car_make: 'Ford',
          car_model: 'Focus',
          car_year: 2008 
        },
        {
          username: 'gregory.watts51@example.com',
          password: 'harrypotter',
          first_name: 'Gregory',
          last_name: 'Watts',
          phone_number: '(383)-474-8220',
          email_address: 'gregory.watts51@example.com',
          age: 21,
          gender: 'Male',
          photo_url: 'https://randomuser.me/api/portraits/men/45.jpg',
          city: 'Denver',
          state: 'CO',
          years_experience: 5,
          hourly_rate: 15,
          surfing: false,
          kayaking: false,
          rock_climbing: false,
          skateboarding: false,
          hiking: false,
          mountain_biking: true,
          skiing: false,
          snowboarding: true,
          background: 'I was on my high school mountain biking and snowboard team.  I currently am a senior at CU Denver studying child development, and plan to be a 4th grade science teacher.',
          education: 'Pursueing bachelors degree and teaching certificate',
          first_aid: true,
          cpr: true,
          lifeguard: false,
          other_certs: '',
          car_make: 'Ford',
          car_model: 'Explorer',
          car_year: 2008
        }
      ]);
    })
    .then (() => {
      return knex.raw('ALTER SEQUENCE nanny_account_info_id_seq RESTART WITH 5;')
    })
};



